kubernetes_event_exporter_chart_version: 2.1.2
cert_manager_clusterissuer_enabled: false
cert_manager_clusterissuer_chart_version: 1.0.0
cert_manager_clusterissuer_values: {}
otcdns_wildcard_certificates: []
# This is the default to keep backwards compatibility
otc_cert_manager_enabled: "{{ otcdns_wildcard_certificates | length > 0 }}"
fluentbit_enabled: true
