---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: monitoring
    kind: Namespace

- name: Create Image pull secret token
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ image_pull_secrets_name }}"
        namespace: monitoring
      data:
        .dockerconfigjson: "{{ image_pull_token_secret }}"

- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
  check_mode: false
  changed_when: false
  tags: prometheus

- include_tasks: prometheus.yml
  vars:
    prometheus_community_values: "{{ prometheus_default_values }}"
  loop: "{{ prometheus_instances }}"
  tags: prometheus

- name: Create service account
  uri:
    url: "{{ grafana_main_domain }}/api/serviceaccounts"
    method: POST
    user: "{{ grafana_adminUser }}"
    password: "{{ grafana_adminPassword }}"
    force_basic_auth: yes
    status_code: 200,201
    body_format: json
    body:
      name: "{{ grafana_sa_name }}"
      role: "{{ grafana_sa_role }}"
  register: sa_response

- name: Create token for service account
  uri:
    url: "{{ grafana_main_domain }}/api/serviceaccounts/{{ sa_response.json.id }}/tokens"
    method: POST
    user: "{{ grafana_adminUser }}"
    password: "{{ grafana_adminPassword }}"
    force_basic_auth: yes
    status_code: 200,201
    body_format: json
    body:
      name: "ansible-token"
  register: token_response

- name: Show token
  debug:
    msg: "Service Account Token: {{ token_response.json.key }}"

- name: Create a team
  community.grafana.grafana_team:
    url: "{{ grafana_main_domain }}"
    grafana_api_key: "{{  }}"
    name: "grafana_working_group"
    email: "foo.bar@example.com"
    state: present

- include_tasks: grafana-dashboards.yml
  tags: prometheus

