---
- name: Create namespace for psql config
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    api_version: v1
    name: "{{ psql_namespace }}"
    kind: Namespace

- name: Create Secret for Postgres configuration
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    template: 'secret.yml.j2'
  register: postgres_secret

- name: Create configmap for config-script
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "psql-{{ psql_name }}-config-script"
        namespace: "{{ psql_namespace }}"
      data:
        config-script: "{{ lookup('template', 'config-script.sh.j2') }}"
  register: postgres_configscript

- name: Create Config Job
  kubernetes.core.k8s:
    state: "present"
    kubeconfig: "{{ kubeconfig }}"
    proxy: "{{ proxy_url | default(omit, true) }}"
    proxy_headers: "{{ proxy_headers | default(omit, true) }}"
    template: 'config-job.yml.j2'
  when: postgres_secret.changed or postgres_configscript.changed or rerun_postgres_config | default (false)