s3_create_bucket_owner: ""
s3_create_bucket_ionos_token: ""
s3_create_bucket_region: "eu-central-2"
s3_create_bucket_url: "https://s3.{{ s3_create_bucket_region }}.ionoscloud.com"
s3_create_bucket_bucket_versioning: false
s3_create_bucket_bucket_policy: "null" # "null" as string sets the policy to absent
s3_create_bucket_bucket_name: "data"
s3_create_bucket_access_key: ""
s3_create_bucket_secret_key: ""
s3_create_bucket_cors_settings: false
s3_create_bucket_allowed_origins:
  - "https://*"
s3_create_bucket_allowed_methods:
  - GET
s3_create_bucket_allowed_headers:
  - "*"
s3_create_bucket_expose_headers: []
s3_create_bucket_max_age_seconds: 3000
s3_create_bucket_lifecycle_rules: []
#  - rule_name: "name-rule"
#    rule_expiration_days: 7
#    rule_noncurrent_version_expiration_days: 9
#    rule_prefix: ""

# sets the 1pw vaults and their respective item fields
s3_create_bucket_1pw_targets: []
#  - credentials_section_name: ""
#    bucket_name_1pw_field_name: ""
#    access_key_1pw_field_name: ""
#    access_secret_1pw_field_name: ""
#    url_1pw_field_name: ""
