
    - name: Generate SSH public keys list for SSHD Users
      set_fact:
        sshd_public_keys: |
          {% set sshd_public_key_map = {} %}
          {% for user in present_users %}
            {% set canonical_hosts = [] %}
            {% if user.permissions.sshd is defined %}
              {% if user.permissions.sshd.hosts is string %}
                {% set hosts = [ user.permissions.sshd.hosts ] %}
              {% else %}
                {% set hosts = user.permissions.sshd.hosts %}
              {% endif %}
              {% for host in hosts %}
                {% set _ = canonical_hosts.extend(lookup('inventory_hostnames', host, wantlist=true)) %}
              {% endfor %}
              {% if inventory_hostname in canonical_hosts %}
                {% set _ = sshd_public_key_map.update({user.name: lookup('file', 'sshkeys/' + user.name + '.pub')}) %}
              {% endif %}
            {% endif %}
          {% endfor %}
          {{ sshd_public_key_map }}
      tags:
        - sshd


    - name: Create {{ sshd_namespace }} namespace
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        api_version: v1
        name: "{{ sshd_namespace }}"
        kind: Namespace
      when: sshd_public_keys | length > 0
      tags:
        - sshd

    - name: Deploy SSHD host keys secret
      kubernetes.core.k8s:
        state: "{{ (sshd_public_keys | length > 0) | ternary('present', 'absent') }}"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        apply: true
        definition:
          apiVersion: onepassword.com/v1
          kind: OnePasswordItem
          metadata:
            name: sshd-host-keys
            namespace: "{{ sshd_namespace }}"
          spec:
            itemPath: "vaults/{{ vault }}/items/sshd-host-keys"
      tags:
        - sshd

    - name: Create docker token secret
      kubernetes.core.k8s:
        state: "{{ (image_pull_token_enabled and sshd_public_keys | length > 0) | ternary('present', 'absent') }}"
        kubeconfig: "{{ kubeconfig }}"
        proxy: "{{ proxy_url | default(omit, true) }}"
        proxy_headers: "{{ proxy_headers | default(omit, true) }}"
        definition:
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: docker-token
            namespace: "{{ sshd_namespace }}"
          data:
            .dockerconfigjson: "{{ image_pull_token_secret }}"
      tags: sshd

    - name: Add dbildungsplattform chart repo
      kubernetes.core.helm_repository:
        name: dbildungsplattform
        repo_url: https://dbildungsplattform.github.io/helm-charts-registry/
      check_mode: false
      changed_when: false
      when: sshd_public_keys | length > 0
      tags: sshd

    - name: Deploy latest version of SSHD chart to update user keys on Cluster
      kubernetes.core.helm:
        state: "{{ (sshd_public_keys | length > 0) | ternary('present', 'absent') }}"
        kubeconfig: "{{ kubeconfig }}"
        name: "{{ sshd_chart }}"
        chart_ref: "dbildungsplattform/{{ sshd_chart }}"
        update_repo_cache: yes
        chart_version: "{{ sshd_chart_version }}"
        release_namespace: "{{ sshd_namespace }}"
        values: "{{ sshd_values }}"
        wait: true
      tags:
        - sshd
